### ISSUE TITLE
Getting this error after latest release

### ISSUE THREAD

**Issue by manishiitg** [VarunGumma/IndicTransTokenizer#15]
Traceback (most recent call last):
File "/home/gcpuser/sky_workdir/translate.py", line 15, in <module>
from IndicTransTokenizer import IndicProcessor, IndicTransTokenizer
File "/home/gcpuser/sky_workdir/IndicTransTokenizer/IndicTransTokenizer/__init__.py", line 4, in <module>
 from .collator import IndicDataCollator
File "/home/gcpuser/sky_workdir/IndicTransTokenizer/IndicTransTokenizer/collator.py", line 8, in <module>
from transformers.data.data_collator import pad_without_fast_tokenizer_warning
ImportError: cannot import name 'pad_without_fast_tokenizer_warning' from 'transformers.data.data_collator' (/opt/conda/lib/python3.10/site-packages/transformers/data/data_collator.py)
ERROR: Job 1 failed with return code list: [1] 
INFO: Job finished (status: FAILED).
Shared connection to 35.246.42.131 closed.

**Comment by VarunGumma** [comment]
Hi @manishiitg , what version of `transformers` are you using?

**Comment by manishiitg** [comment]
transformers==4.33.2

**Comment by VarunGumma** [comment]
@manishiitg , we just updated the `requirements`, and please try with `transformers>=4.39.3`

**Comment by manishiitg** [comment]
works now!
