### ISSUE TITLE
Issue with editable installation

### ISSUE THREAD

**Issue by Manikantan-S** [VarunGumma/IndicTransTokenizer#3]
I tried setting up Indictrans2 for translation purposes in my project and also tried to import this tokeniser in the same repo , Can someone please help with my errors
Laptop: Windows
![image](https://github.com/VarunGumma/IndicTransTokenizer/assets/111214511/5dc67ca4-413b-4aeb-96fe-3999764d3a7c)

**Comment by arpanraj** [comment]
I had same problem in windows! I solved it by updating setup.py line 21
```
with open("README.md", "r",errors='ignore') as fh: 
```
I think it's okay to ignore unsupported characters in readme file which gets added in description of package.

**Comment by VarunGumma** [comment]
@arpanraj , thank you for the suggestion and fix. I have added the same to the `setup.py` file. Hope there will not be any more issues.

**Comment by Manikantan-S** [comment]
Thanks  a lot  @VarunGumma @arpanraj it resolved  with the solution
