### ISSUE TITLE
Create a public python package

### ISSUE THREAD

**Issue by kurianbenoy** [VarunGumma/IndicTransTokenizer#4]
Please host this package in pypi

**Comment by VarunGumma** [comment]
Hi @kurianbenoy , 

We tried to do that earlier, but the dependency on [IndicNLP library](https://github.com/VarunGumma/indic_nlp_library) repo throws an error, while creating and uploading the `pypi` files. Hence, we only have an editable installable version for now. Any leads on how to mitigate this issue are welcome!
