### ISSUE TITLE
Indicproessor issue

### ISSUE THREAD

**Issue by Manikantan-S** [VarunGumma/IndicTransTokenizer#8]
The code was running fine till yesterday now indicprocessor is not getting initialised pls help due to that error in IndicTransTokenizer
![image](https://github.com/VarunGumma/IndicTransTokenizer/assets/111214511/d153bfee-409f-49dc-b3e8-4b40379a3a8a)

**Comment by jaygala24** [comment]
You have not installed the IndicTransTokenizer package. Please follow the installation instructions.
