### ISSUE TITLE
Unable to import Indicprocessor from IndicTransTokenizer

### ISSUE THREAD

**Issue by alans3321** [VarunGumma/IndicTransTokenizer#9]
Below are the code which I ran;

```
!git clone https://github.com/VarunGumma/IndicTransTokenizer
%cd IndicTransTokenizer
```
```
!git clone https://github.com/VarunGumma/indic_nlp_library.git

%cd indic_nlp_library

```
```
!python3 -m pip install nltk sacremoses pandas regex mock transformers>=4.33.2 mosestokenizer
!python3 -c "import nltk; nltk.download('punkt')"
!python3 -m pip install bitsandbytes scipy accelerate datasets
!python3 -m pip install sentencepiece


!python3 -m pip install --editable ./
%cd ..
```
```
from IndicTransTokenizer import  IndicProcessor,IndicTransTokenizer
```
![image](https://github.com/VarunGumma/IndicTransTokenizer/assets/87294936/f61307e0-c720-4a06-9c85-46c248b5575b)

Unable to import IndicProcessor, though IndicTransTokenizer is getting imported. Kindly help

**Comment by PranjalChitale** [comment]
This is because you have not installed the IndicTransTokenizer package.

Please navigate inside the `IndicTransTokenizer` directory and do `!python3 -m pip install --editable ./` as described in the [readme](https://github.com/VarunGumma/IndicTransTokenizer?tab=readme-ov-file#configuration).
